changesetBaseRefs:
  - main
  - origin/main
  - upstream/main
  - refs/remotes/origin/main
  - +refs/heads/main

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs
