name: 'Setup Node with Cached Dependencies'
description: 'Set up Node.js and install dependencies with caching'
runs:
  using: 'composite'
  steps:
    - name: "Set up node"
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version-file: .nvmrc
        
    - name: "Setup pnpm"
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
    - name: "Get pnpm store directory"
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: "Setup cache"
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    - name: "Install dependencies"
      run: pnpm install --frozen-lockfile
      shell: bash
