name: Testing Atlas Build

on:
    pull_request:
        paths:
            - "packages/theming/atlas/**"

jobs:
    test:
        name: "Testing Atlas Build"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@v2
              with:
                  submodules: false
            - name: "Installing dependencies"
              run: npm install
            - name: "Running Atlas build"
              run: |
                  pwd
                  cd packages/theming/atlas
                  pwd
                  npm run build
