name: Testing Atlas Reference App

on:
    push:
        branches: [master]
        paths:
            - "packages/theming/atlas/**"
    pull_request:
        branches: [master]
        paths:
            - "packages/theming/atlas/**"

jobs:
    test:
        name: "Testing Atlas Reference App"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@v2
              with:
                  submodules: true
            - name: "Defining cache"
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            - name: "Installing dependencies"
              run: npm install
            - name: "Executing E2E screenshot tests"
              run: |
                  cd packages/theming/atlas
                  npm run test:e2e
            - name: "Fixing files permissions"
              if: failure()
              run: |
                  sudo find ${{ github.workspace}}/packages/theming -type d -exec chmod 755 {} \;
                  sudo find ${{ github.workspace}}/packages/theming -type f -exec chmod 644 {} \;
            - name: "Archive test screenshot results"
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: test-screenshot-results
                  path: |
                      ${{ github.workspace}}/packages/theming/atlas/tests/e2e/screenshot-results/diff/p/*.png
                      ${{ github.workspace}}/packages/theming/atlas/tests/e2e/screenshot-results/actual/p/*.png
                  if-no-files-found: error
