name: Create widget release

on:
    workflow_dispatch:
        inputs:
            widget-name:
                description: "Widget to release"
                required: true

jobs:
    release:
        name: "Create widget release"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@v2
              with:
                  submodules: false
            - name: "Installing dependencies"
              run: npm install
            - name: "Building ${{ github.event.inputs.widget-name }} widget"
              run: "npm run release -- --scope '${{ github.event.inputs.widget-name }}'"
            - name: "Creating ${{ github.event.inputs.widget-name }} widget release"
              run: "npm run release-github:widget '${{ github.event.inputs.widget-name }}'"
              env:
                  GH_USERNAME: ${{ secrets.GH_USERNAME }}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
                  GH_PAT: ${{ secrets.GH_PAT }}
