name: Marketplace Release

on:
    push:
        tags:
            - "*-web-v*"
            - "*-native-v*"
            - "*-hybrid-v*"

jobs:
    publish_release:
        name: "Marketplace Release"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@v2
              with:
                  submodules: false
            - name: "Defining Environment Variables"
              id: variables
              run: echo "::set-output name=tag::$(git tag --points-at HEAD)"
            - name: "Defining lerna scope"
              uses: jungwinter/split@v1
              id: scope
              with:
                  msg: ${{ steps.variables.outputs.tag }}
                  separator: "-v"
            - name: "Installing dependencies"
              run: npm install
            - name: "Check changes and publish package ${{ steps.variables.outputs.tag }}"
              run:
                  TAG=${{ steps.variables.outputs.tag }} MARKETPLACE_USERNAME=${{ secrets.MARKETPLACE_USERNAME }}
                  MARKETPLACE_API_KEY=${{ secrets.MARKETPLACE_API_KEY }} npm run release:marketplace -- --scope '${{
                  steps.scope.outputs._0 }}'
            - name: "Send slack msg on failure"
              if: ${{ failure() }}
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_CHANNEL: ${{ secrets.SLACK_MULTIXP_CHANNEL }}
                  SLACK_COLOR: ${{ job.status }}
                  SLACK_ICON: ${{ secrets.WEBCONTENT_BOT_IMAGE }}
                  SLACK_MESSAGE:
                      "Something went wrong while uploading version ${{ steps.scope.outputs._1 }} of package ${{ steps.scope.outputs._0 }} to the marketplace. <https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|More info..>"
                  SLACK_TITLE: ":alert: Failure"
                  SLACK_USERNAME: ${{ secrets.WEBCONTENT_BOT_NAME }}
                  SLACK_WEBHOOK: ${{ secrets.SLACK_MULTIXP_WEBHOOK }}
                  SLACK_FOOTER: "Created by Aliens"
                  MSG_MINIMAL: true
