name: Ensure SHA pinned actions

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"

jobs:
  harden_security:
    name: Check SHA in GH Actions
    runs-on: ubuntu-latest
    steps:
      - name: "Checking-out code"
        uses: actions/checkout@b44b924715cf27938426f1e1b8ed5fe31492eb67 # v4
        with:
          submodules: false
      - name: "Ensure SHA pinned actions"
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@0b552a197e44b819629237e065d781f5ca691460 # v1.1.1
