name: Ensure SHA pinned actions

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"

jobs:
  harden_security:
    name: Check SHA in GH Actions
    runs-on: ubuntu-latest
    steps:
      - name: "Checking-out code"
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: false
      - name: "Ensure SHA pinned actions"
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@5c6142ee95066fc1ae17c5e2713712f5876d0689 # v1.1.2
